#!/sbin/openrc-run

description="Fake job for hildon-desktop"

depend() {
    need xsession
}

start_pre() {
    [ -e /tmp/ACT_DEAD ] && exit 1

    ebegin "Wating for hildon-desktop to start"

    while [ ! -e /tmp/hildon-desktop/desktop-started.stamp ]
    do
        sleep 2
    done
    # This is to make sure it's really functional by the time user
    # gets to use it.
    sleep 5
}

start() {
    eend 0
}
